### ISSUE TITLE
Sort doesn't always work

### ISSUE THREAD

**Issue by flaming910** [Raymoclaus/RedundantTalismans#1]
So if you import from file, click calculate, and then sort its fine.
But then if you import more stuff/do another calculate, you can no longer sort things

**Comment by Raymoclaus** [comment]
I can reproduce this. Thanks for finding it. I will get around to fixing it, but for now a workaround is just closing and reopening the program which doesn't take long.

**Comment by Raymoclaus** [comment]
Sorry for taking a while to get around to this, but it is now fixed in the latest release.
