### ISSUE TITLE
Tool is not accurate/makes a wrong decision

### ISSUE THREAD

**Issue by Erdnussflip007** [Raymoclaus/RedundantTalismans#2]
[This](https://imgur.com/a/XSrHpDt) happened yesterday. The tool says (Wirebug Whisperer,1,,0,2,2,0) is redundant because of (Hunger Resistance,1,Wirebug Whisperer,1,3,1,0).

This is wrong, because with the first i can achieve Wirebug Whisperer 1,Attack Boost 2, while with the second one I can only fit one Attackboost and got a level 1 Slot left over.

**Comment by Raymoclaus** [comment]
Thanks for finding this. It has been fixed in v1.1.3
