### ISSUE TITLE
Update for Title Update 2?

### ISSUE THREAD

**Issue by onionpowder2** [Raymoclaus/RedundantTalismans#3]
Could this happen at some point? I'd greatly appreciate it. I tried making an updated version of the decoration list, but actually implementing it into the program is beyond my knowledge. I'll attach it to this post if it'd help at all. As a note, I used the old name for Chain Crit in this list, but the skill was renamed Burst in Title Update 2.
[decorations updated.txt](https://github.com/Raymoclaus/RedundantTalismans/files/9697064/decorations.updated.txt)

**Comment by Raymoclaus** [comment]
Thanks for your effort. That does help. I'll try and get an update out in a few days.

**Comment by Raymoclaus** [comment]
The new decorations have now been added. Your list was very helpful and even matched the formatting of the original list. I changed Chain Crit to Burst.
